form_designer/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from views import (FormCreateView, FormUpdateView,
        TabCreateView, TabUpdateView, TabDeleteView,
        WidgetCreateView, WidgetUpdateView, WidgetDeleteView)


urlpatterns = patterns('',
    url(r'form/create/$',
        login_required(FormCreateView.as_view()),
        name='form_designer_form_create'),
    url(r'form/(?P<pk>\d+)/update/$',
        login_required(FormUpdateView.as_view()),
        name='form_designer_form_update'),

    # Tabs
    url(r'tab/create/$',
        login_required(TabCreateView.as_view()),
        name='form_designer_tab_create'),
    url(r'tab/update/$',
        login_required(TabUpdateView.as_view()),
        name='form_designer_tab_update'),
    url(r'tab/delete/$',
        login_required(TabDeleteView.as_view()),
        name='form_designer_tab_delete'),

    # Widgets
    url(r'widget/create/$',
        login_required(WidgetCreateView.as_view()),
        name='form_designer_widget_create'),
    url(r'widget/update/$',
        login_required(WidgetUpdateView.as_view()),
        name='form_designer_widget_update'),
    url(r'widget/delete/$',
        login_required(WidgetDeleteView.as_view()),
        name='form_designer_widget_delete'),
)

form_designer/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django import forms
from django.forms.models import modelform_factory
from django.template.defaultfilters import slugify
from django.db.models import signals

from picklefield.fields import PickledObjectField
from polymodels.models import PolymorphicModel
from crispy_forms.layout import Layout, Fieldset

from utils import import_class


__all__ = ['Form', 'Tab', 'Widget',
    'InputWidget', 'TextareaWidget', 'ChoiceWidget']


class Form(models.Model):
    name = models.CharField(max_length=200)
    verbose_name = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User')

    def to_crispy(self):
        layout = Layout()
        for tab in self.tab_set.all():
            layout.fields.append(tab.to_crispy())

        return layout

    def get_form_class(self, bases=None, form_class_name=None, attrs=None):
        if bases is None:
            bases = (forms.Form,)

        if form_class_name is None:
            form_class_name = 'Form%s' % self.pk

        widgets = Widget.objects.filter(tab__form=self).select_subclasses()
        attributes = {w.name: w.field_instance() for w in widgets}

        if attrs:
            attributes.update(attrs)

        form_class = type(form_class_name, bases, attributes)
        return form_class

    @property
    def fields(self):
        for tab in self.tab_set.all():
            for field in tab.field_set.all():
                yield field

    def update_from_dict(self, data):
        self.name = data[u'name'].strip()

        self.tab_set.all().delete()
        order = 0

        for tab_data in data[u'tabs']:
            tab = Tab(name=tab_data[u'name'].strip(), form=self, order=order)
            tab.update_from_dict(tab_data)
            self.tab_set.add(tab)
            order += 1

    def __unicode__(self):
        return self.name

    def get_update_url(self):
        return reverse('form_designer_form_update', args=(self.pk,))

    class Meta:
        ordering = ('name',)


class Tab(models.Model):
    name = models.CharField(max_length=200)
    verbose_name = models.CharField(max_length=200)
    form = models.ForeignKey(Form)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ('order', 'pk')

    def to_crispy(self):
        fieldset = Fieldset(self.name)
        for field in self.field_set.all():
            fieldset.fields.append(field.to_crispy())
        return fieldset

    def update_from_dict(self, data):
        self.fields = []
        order = 0

        for field_data in data[u'fields']:
            field = Field(
                tab=self,
                name=field_data[u'name'].strip(),
                kind=field_data[u'kind'].strip(),
                required=field_data[u'required'],
                order=order,
                verbose_name=field_data[u'verbose_name'].strip(),
                help_text=field_data[u'help_text'].strip()
            )
            field.save()
            self.field_set.add(field)
            order += 1

    def __unicode__(self):
        return self.name


class Widget(PolymorphicModel):
    tab = models.ForeignKey(Tab)
    name = models.CharField(max_length=200)
    verbose_name = models.CharField(max_length=200)
    help_text = models.TextField(blank=True)
    required = models.BooleanField()
    order = models.IntegerField()

    @property
    def configuration_form_class(self):
        """ Return the form class to configure this widget. """

        from forms import WidgetForm  # avoid recursion
        return modelform_factory(self.__class__, form=WidgetForm)

    def configuration_form_instance(self, request):
        """ Return the form instance to configure this widget. """
        form_class = self.configuration_form_class

        if request.method == 'POST':
            form = form_class(request.POST, instance=self)
        else:
            form = form_class(instance=self)

        return form

    def field_class(self):
        return import_class(self.field_class_path)

    def widget_class(self):
        return import_class(self.widget_class_path)

    def field_kwargs(self):
        return {
            'label': self.verbose_name,
            'required': self.required,
            'help_text': self.help_text,
            'widget': self.widget_class()(**self.widget_kwargs()),
        }

    def widget_kwargs(self):
        return {}

    def field_instance(self):
        return self.field_class()(**self.field_kwargs())

    def __unicode__(self):
        return self.verbose_name

    def update_url(self):
        return reverse('form_designer_widget_update', args=(self.pk,))

    @classmethod
    def create_url(self):
        return reverse('form_designer_widget_create')

    class Meta:
        ordering = ('order',)


class InputWidget(Widget):
    max_length = models.IntegerField(default=255)
    field_class_path = 'django.forms.fields.CharField'
    widget_class_path = 'django.forms.widgets.TextInput'

    def field_kwargs(self):
        kwargs = super(InputWidget, self).field_kwargs()
        kwargs['max_length'] = self.max_length
        return kwargs

    class Meta:
        verbose_name = _(u'Short text input')
        verbose_name_plural = _(u'Short text inputs')


class IntegerWidget(Widget):
    min_value = models.IntegerField(null=True, blank=True)
    max_value = models.IntegerField(null=True, blank=True)
    field_class_path = 'django.forms.fields.IntegerField'
    widget_class_path = 'django.forms.widgets.TextInput'

    def field_kwargs(self):
        kwargs = super(IntegerWidget, self).field_kwargs()
        kwargs['max_value'] = self.max_value
        kwargs['min_value'] = self.min_value
        return kwargs

    class Meta:
        verbose_name = _(u'Integer input')
        verbose_name_plural = _(u'Integer inputs')


class DecimalWidget(Widget):
    min_value = models.IntegerField(null=True, blank=True)
    max_value = models.IntegerField(null=True, blank=True)
    max_digits = models.IntegerField(null=True, blank=True)
    decimal_places = models.IntegerField(null=True, blank=True)
    field_class_path = 'form_designer.fields.DecimalField'
    widget_class_path = 'django.forms.widgets.TextInput'

    def field_kwargs(self):
        kwargs = super(DecimalWidget, self).field_kwargs()
        kwargs['max_value'] = self.max_value
        kwargs['min_value'] = self.min_value
        kwargs['max_digits'] = self.max_digits
        kwargs['decimal_places'] = self.decimal_places
        return kwargs

    class Meta:
        verbose_name = _(u'Decimal input')
        verbose_name_plural = _(u'Decimal inputs')


class TextareaWidget(Widget):
    field_class_path = 'django.forms.fields.CharField'
    widget_class_path = 'django.forms.widgets.Textarea'

    class Meta:
        verbose_name = _(u'Long text input')
        verbose_name_plural = _(u'Long text inputs')


class EmailWidget(Widget):
    field_class_path = 'django.forms.fields.EmailField'
    widget_class_path = 'django.forms.widgets.TextInput'

    class Meta:
        verbose_name = _(u'Email input')
        verbose_name_plural = _(u'Email inputs')


class BooleanWidget(Widget):
    field_class_path = 'django.forms.fields.BooleanField'
    widget_class_path = 'django.forms.widgets.CheckboxInput'

    class Meta:
        verbose_name = _(u'Checkbox input')
        verbose_name_plural = _(u'Checkbox inputs')


class ChoiceWidget(Widget):
    choices = PickledObjectField()
    multiple = models.BooleanField()

    class Meta:
        verbose_name = _(u'Choice select')
        verbose_name_plural = _(u'Choice selects')


def auto_name(sender, instance, **kwargs):
    if not issubclass(sender, (Form, Tab, Widget)):
        return

    if not instance.name:
        instance.name = slugify(instance.verbose_name).replace('-', '_')

        check = instance.__class__.objects.all()

        if isinstance(instance, Tab):
            check = check.filter(form=instance.form)
        elif isinstance(instance, Widget):
            check = check.filter(tab__form=instance.tab.form)

        if instance.pk:
            check = instance.__class__.objects.exclude(pk=instance.pk)

        while check.filter(name=instance.name).count():
            instance.name = instance.name + '_'

signals.pre_save.connect(auto_name)


def first_tab(sender, instance, created, **kwargs):
    if not instance.tab_set.count():
        instance.tab_set.create(verbose_name=instance.verbose_name)
signals.post_save.connect(first_tab, sender=Form)

form_designer/templates/form_designer/base.html
{% extends 'site_base.html' %}

form_designer/templates/form_designer/form_create.html
{% extends 'form_designer/base.html' %}

{% load crispy_forms_tags i18n %}

{% block body %}
    <h1>{% trans 'Create form' %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'Submit' %}" />
    </form>
{% endblock %}

form_designer/templates/form_designer/form_update.html
{% extends 'form_designer/base.html' %}

{% load i18n %}
{% load url from future %}

{% block extra_head %}
    <link type="text/css" href="{{ STATIC_URL }}form_designer/form_update.css" rel="stylesheet" />
{% endblock %}

{% block extra_body %}
    {{ block.super }}

    {% block jquery_cookie %}
        <script src="{{ STATIC_URL }}form_designer/jquery.cookie.js" type="text/javascript"></script>
    {% endblock %}
    {% block jquery_ui %}
        <script src="{{ STATIC_URL }}form_designer/jquery-ui.js" type="text/javascript"></script>
    {% endblock %}
    {% block js_var_csrftoken %}
        <script type="text/javascript">
            var csrftoken = $.cookie('csrftoken');
            {% include 'form_designer/origin_security.js' %}
        </script>
    {% endblock %}

    <script src="{{ STATIC_URL }}form_designer/form_update.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        var formUpdate = new yourlabs.FormUpdate({
            formUpdateUrl: '{{ request.widget_class }}',
            widgetCreateUrl: '{% url 'form_designer_widget_create' %}',
            widgetUpdateUrl: '{% url 'form_designer_widget_update' %}',
            widgetDeleteUrl: '{% url 'form_designer_widget_delete' %}',
            tabCreateUrl: '{% url 'form_designer_tab_create' %}',
            tabUpdateUrl: '{% url 'form_designer_tab_update' %}',
            tabDeleteUrl: '{% url 'form_designer_tab_delete' %}',
        });
        formUpdate.init();
        formUpdate.bind();
    });
    </script>
{% endblock %}

{% block body %}
    <div class="form-info">
        <h1 id="form-name" contenteditable="true">{{ form.verbose_name }}</h1>
        <input type="hidden" id="form-pk" value="{{ form.pk }}" />
    </div>

    <div class="form outer">
        <div class="enabled-form inner">
            <ul class="nav nav-tabs form-tabs">
                {% for tab in form.tab_set.all %}
                <li data-pk="{{ tab.pk }}">
                    <a href="#tab-{{ tab.pk }}" data-toggle="tab">
                        <span class="handle">handle</span>
                        <span contenteditable="true" class="name">{{ tab.verbose_name }}</span>
                        <span class="remove">delete</span>
                    </a>
                </li>
                {% endfor %} 
                <li class="new-tab">
                    +
                </li>
            </ul>

            <div class="tab-list">
                {% for tab in form.tab_set.all %}
                <div class="tab-pane" id="tab-{{ tab.pk }}">
                    <table class="fieldset">
                        {% for field in tab.widget_set.all %}
                        <tr class="field {{ field.kind }}" id="field-{{ field.name }}"
                            data-pk="{{ field.pk }}">
                            <td class="handle">
                                <span class="handle">handle</span>
                            </td>
                            <td class="required">
                                <input disabled="disabled" type="checkbox" {% if field.required %}checked="checked"{% endif %} />
                            </td>
                            <td class="verbose-name">
                                {{ field.verbose_name }}
                            </td>
                            <td class="help">
                                <span class="help">help</span>
                            </td>
                            <td class="help-text">
                                {{ field.help_text|safe }}
                            </td>
                            <td class="configuration">
                                <span class="configuration">configuration</span>
                            </td>
                            <td class="remove">
                                <span>delete</span>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="toolbox-outer">
    	<h3 class="filter_title">{% trans 'Toolbox' %}</h3>
        <table>
            {% for widget_class, class in widget_classes.items %}
            <tr class="field {{ widget_class }} new-field" id="new-field-{{ widget_class }}" data-widget-class="{{ widget_class }}">
                <td class="add">
                    <span class="add">add</span>
                </td>
                <td class="verbose-name" title="{{ widget_class.META.verbose_name }}">
                    {{ class.META.verbose_name }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="modal hide fade" id="field-configuration">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="title">{% trans 'Form field configuration' %}</h3>
        </div>
        <div class="modal-body">
            <form>
            </form>
        </div>
        <div class="modal-footer">
            <a style="float:left" href="#" class="btn cancel btn-danger">{% trans 'Cancel' %}</a>
            <a href="#" class="btn save btn-primary">{% trans 'Save' %}</a>
        </div>
    </div>

    <div class="modal hide fade" id="delete-field">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="title">{% trans 'Delete field' %}</h3>
        </div>
        <div class="modal-body">
            <p>{% trans 'Are you sure you want to delete field' %} <span class="field-name"></span> ?</p>
        </div>
        <div class="modal-footer">
            <a style="float:left" href="#" data-dismiss="modal" class="btn cancel btn-danger">{% trans 'Cancel' %}</a>
            <a href="#" class="btn save btn-primary">{% trans 'Delete' %}</a>
        </div>
    </div>

    <div class="modal hide fade" id="new-tab">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="title">{% trans 'Create tab' %}</h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <label>{% trans 'Title' %}</label>
                <form>
                    <div class="controls">
                        <input type="text" placeholder="{% trans 'Type the tab title here' %}" name="verbose_name"/>
                        <span class="help-block">{% trans 'You will then be able to change it by clicking on the tab title in the form editor.' %}</span>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <a style="float:left" href="#" class="btn cancel btn-danger">{% trans 'Cancel' %}</a>
            <a href="#" class="btn save btn-primary">{% trans 'Create' %}</a>
        </div>
    </div>

    <div class="modal hide fade" id="delete-tab">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="title">{% trans 'Delete tab' %}</h3>
        </div>
        <div class="modal-body">
            <p>{% trans 'Are you sure you want to delete tab' %} <span class="tab-name"></span> ?</p>
        </div>
        <div class="modal-footer">
            <a style="float:left" href="#" data-dismiss="modal" class="btn cancel btn-danger">{% trans 'Cancel' %}</a>
            <a href="#" class="btn save btn-primary">{% trans 'Delete' %}</a>
        </div>
    </div>

{% endblock %}

form_designer/templates/form_designer/widget_form.html
{% load bootstrap_tags %}

{{ form|as_bootstrap }}